name: 'Saluda'
description: 'Greet someone and record the time' 
outputs:
  time: # id of output
    description: 'The time we greeted you'
  nombre: # id of output
    description: 'Nombre'
runs:
  using: 'docker'
  image: 'Dockerfile'
  